#!/usr/bin/env python3
"""Load: data/clean/*.json -> Postgres, idempotently (truncate-and-reload).

The whole load runs in one transaction: lookups first (FK order), then the fact
table, then a load_manifest row whose row_hash is the sha256 over sorted
"reservation_id|stay_date|financial_status" lines — the same fingerprint
/verify and scripts/compute_load_fingerprint.py use.

Also writes etl/SCRAPE_MANIFEST.json from the extract metadata.
"""
from __future__ import annotations

import hashlib
import json
import os
import pathlib
import sys

import psycopg

ROOT = pathlib.Path(__file__).resolve().parents[1]
CLEAN = ROOT / "data" / "clean"
RAW = ROOT / "data" / "raw"

DATABASE_URL = os.environ.get(
    "DATABASE_URL", "postgresql://hackathon:hackathon@localhost:5432/hotel_hackathon"
)

LOOKUP_ORDER = [
    "room_type_lookup",
    "market_code_lookup",
    "channel_code_lookup",
    "rate_plan_lookup",
    "market_macro_group_history",
]

FACT_COLUMNS = [
    "reservation_id", "arrival_date", "departure_date", "stay_date", "property_date",
    "reservation_status", "financial_status", "create_datetime", "cancellation_datetime",
    "guest_country", "is_block", "is_walk_in", "number_of_spaces", "space_type",
    "market_code", "channel_code", "source_name", "rate_plan_code",
    "daily_room_revenue_before_tax", "daily_total_revenue_before_tax",
    "nights", "adr_room", "lead_time", "company_name", "travel_agent_name",
]


def row_hash(facts: list[dict]) -> str:
    lines = sorted(
        f"{r['reservation_id']}|{r['stay_date']}|{r['financial_status']}" for r in facts
    )
    return hashlib.sha256("\n".join(lines).encode("utf-8")).hexdigest()


def insert_rows(cur, table: str, rows: list[dict], columns: list[str]) -> None:
    placeholders = ", ".join(["%s"] * len(columns))
    sql = f"insert into public.{table} ({', '.join(columns)}) values ({placeholders})"
    cur.executemany(sql, [[r[c] for c in columns] for r in rows])


def main() -> None:
    meta = json.loads((RAW / "meta.json").read_text())
    facts = json.loads((CLEAN / "reservations_hackathon.json").read_text())
    fingerprint = row_hash(facts)

    with psycopg.connect(DATABASE_URL) as conn, conn.cursor() as cur:
        cur.execute(
            "truncate public.reservations_hackathon, "
            + ", ".join(f"public.{t}" for t in LOOKUP_ORDER)
        )
        for table in LOOKUP_ORDER:
            rows = json.loads((CLEAN / f"{table}.json").read_text())
            insert_rows(cur, table, rows, list(rows[0].keys()))
            print(f"loaded {table}: {len(rows)}")
        insert_rows(cur, "reservations_hackathon", facts, FACT_COLUMNS)
        print(f"loaded reservations_hackathon: {len(facts)}")
        cur.execute(
            """insert into public.load_manifest
               (dataset_revision, scraped_at, source_url, row_hash)
               values (%s, %s, %s, %s)""",
            (meta["dataset_revision"], meta["scraped_at"], meta["source_url"], fingerprint),
        )
        conn.commit()

    ids = sorted(set(meta["reservation_ids"]))
    ids_sha = hashlib.sha256("\n".join(ids).encode("utf-8")).hexdigest()
    manifest = {
        "anchor_date": meta["anchor_date"],
        "pages_scraped": meta["pages_scraped"],
        "reservation_ids_count": len(ids),
        "reservation_ids_sha256": ids_sha,
        "notes": "Generated by etl/load.py; reconciled against /verify on scrape day.",
    }
    out = ROOT / "etl" / "SCRAPE_MANIFEST.json"
    out.write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"wrote {out.relative_to(ROOT)}")
    print(f"row_hash={fingerprint}")


if __name__ == "__main__":
    sys.exit(main())
